### ISSUE TITLE
Fedora.sh -> fedora.sh

### ISSUE THREAD

**Issue by instkoff** [Avdushin/GOAPPLE#1]
Скрипт не стартует из за разных имен файлов.

**Comment by Avdushin** [comment]
> instkoff

Добрый день, вы использовали gui или cli клиент программы или пытались запустить вручную?

**Comment by Avdushin** [comment]
> Скрипт не стартует из за разных имен файлов.

Добрый вечер, благодарю за помощь. 
Сейчас вроде как всё должно работать правильно.
