### ISSUE TITLE
Hello, Dear Avdushin!

### ISSUE THREAD

**Issue by Fuhrerbaumanki** [Avdushin/GOAPPLE#10]
After running your utility and restarting my PC, i3wm stopped working.  When I press Ctrl+enter I get an infinite download of kitty.  I've tried running your script again and restarting the computer a few times, but that didn't help.  Help me please. 
UPD:
I use Arch, btw![IMG_20230916_201255.jpg](https://github.com/Avdushin/GOAPPLE/assets/142431169/f9f59f96-8be9-4465-9ba4-f6430be37f15)

![IMG_20230916_201248.jpg](https://github.com/Avdushin/GOAPPLE/assets/142431169/8e9fccdb-9dbf-40b0-9872-53ad174b8bdc)

UPD 2:
Was able to launch floating, But the result leaves much to be desired: it turns out that after launch Goapple, rofi It was not installed, I had to install it manually, the Internet is not displayed, some of the modules Polybar Also, I will continue to look for a solution, maybe I can really fix it myself. I will write about the results here

**Comment by Avdushin** [comment]
@Fuhrerbaumanki Greetings! Thank you for your feedback about the utility. At the moment, its development is frozen (the process of changing the architecture has been started, which has not been finalized, which, as you may have noticed, negatively affects the work of the utility). I apologize for this...
If you are interested in trying the utility, it is better to use its first CLI version (in your case, the Manjaro/Arch build) for now

Here is a link to the CLI solution - https://github.com/Avdushin/GOAPPLE-CLI.

**Comment by Fuhrerbaumanki** [comment]
> @Fuhrerbaumanki Greetings! Thank you for your feedback about the utility. At the moment, its development is frozen (the process of changing the architecture has been started, which has not been finalized, which, as you may have noticed, negatively affects the work of the utility). I apologize for this...
> If you are interested in trying the utility, it is better to use its first CLI version (in your case, the Manjaro/Arch build) for now
> 
> Here is a link to the CLI solution - https://github.com/Avdushin/GOAPPLE-CLI.

Thanks for the answer! I really liked your application, it’s really great, and unfortunately I was not the best user((. I’m embarrassed to admit, but I installed Cli Version, but it did not work due to... The fact that I did not include the user repository, and then wrote here. In any case, I already found a solution. Thank you for your work!

**Comment by Fuhrerbaumanki** [comment]
> @Fuhrerbaumanki Greetings! Thank you for your feedback about the utility. At the moment, its development is frozen (the process of changing the architecture has been started, which has not been finalized, which, as you may have noticed, negatively affects the work of the utility). I apologize for this...
> If you are interested in trying the utility, it is better to use its first CLI version (in your case, the Manjaro/Arch build) for now
> 
> Here is a link to the CLI solution - https://github.com/Avdushin/GOAPPLE-CLI.

Thanks for the answer! I really liked your application, it’s really great, and unfortunately I was not the best user((. I’m embarrassed to admit, but I installed Cli Version, but it did not work due to... The fact that I did not include the user repository, and then wrote here. In any case, I already found a solution. Thank you for your work!

**Comment by Avdushin** [comment]
@Fuhrerbaumanki it's okay, that's why I exist - the author, to help figure it out)
I hope my works will be useful to you. Have a nice day 😃
